# Generated by Django 4.1.5 on 2023-01-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "SUPER_ADMIN"),
                    ("ADMIN", "ADMIN"),
                    ("CUSTOMER", "CUSTOMER"),
                    ("VENDOR", "VENDOR"),
                    ("CARRIER", "CARRIER"),
                    ("EXECUTIVE", "EXECUTIVE"),
                    ("EDITOR", "EDITOR"),
                    ("VIEWER", "VIEWER"),
                ],
                default="CUSTOMER",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
