# Generated by Django 4.1.5 on 2023-01-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "ADMIN"), ("CUSTOMER", "CUSTOMER")], max_length=20
            ),
        ),
    ]
