# Generated by Django 4.1.5 on 2023-01-18 04:01

import common.utils.uid_generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uid",
                    models.CharField(
                        db_index=True,
                        default=common.utils.uid_generator.new_uid,
                        max_length=11,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("otp", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("expiry_at", models.DateTimeField()),
                ("is_expired", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
