# Generated by Django 4.1.5 on 2023-01-17 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="station",
            field=models.OneToOneField(
                default="zwOySF2SZLI",
                on_delete=django.db.models.deletion.CASCADE,
                to="stations.station",
            ),
            preserve_default=False,
        ),
    ]
